### ISSUE TITLE
Build Tauri app on CI

### ISSUE THREAD

**Issue by moreirathomas** [benchttp/desktop#12]
## Description

Building Tauri requires a Rust environment. We must adapt our CI to be compatible.

## Tasks

- [x] configure rust env
- [x] execute `npm run build` after test, lint and `web:build` (catch js errors early)
- [x] copy engine binaries before building (or else workflow fails!)

## Suggestions

It is an expensive operation, it may be worth considering another workflow. It would use a different trigger. The goal is to trigger the expensive workflow only when it is relevant (i.e. not on every push where only ui stuff has changed).

**Comment by moreirathomas** [comment]
Current solution to fail early:

- test for the front end (lint, test react, build vite)
- if this passes, build tauri
