### ISSUE TITLE
Use `useRunStream` to start the run and define the correct data flow through components

### ISSUE THREAD

**Issue by moreirathomas** [benchttp/desktop#35]
## Description

With the new components being created and the ui becoming what is should be given the mockups, we should drop `examples/SimpleStream` component and actually connect the data to the correct components.

## Tasks

- [x] delete `examples/SimpleStream`
- [ ] build a config object from a user form
- [x] provide the config object to a component which can call `start(config)` (from hook `useRunStream`)
- [x] display the progress status from `progress`
- [x] handle stop via `stop`
- [x] ~handle reset via `reset`~ handle reset before restarting
- [x] display results from `report`
- [x] display error if any from `error`

## Suggestions

Instead of doing all of the piping of the data in a single unit of work, we might start to use `useRunStream` asap in the components as they are built. 

This would prevent us from doing a "big bang" pr that should make the things work at the last moment. Instead it would allow to incrementally improve the ui while keeping the entire behavior right.

We might want to start by making the component that will call to `useRunStream` and hold the state.

Note that within the scope of the mvp, we should not be concerned with the persistence of the state between runs or page reloads. **It is more important to simply get the run working with the new ui asap** and keep the persistence layer (a store it would seem) for a later iteration.
